### ISSUE TITLE
Chapter-2에 ./data/example_dataset.tsv가 없네요

### ISSUE THREAD

**Issue by moon5756** [bjpublic/PyTorch#1]
큰 문제는 아니지만 06-summary 코드를 위한 notebooks/Chapter-2/data/example_dataset.tsv 파일이 없네요

**Comment by bjpublic** [comment]
안녕하세요~ 답변이 늦어 죄송합니다. 해당 파일은 다시 올렸으니 확인바랍니다.
감사합니다.
